repos:
  # Detect secrets
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.secrets.baseline']

  # Local hooks
  - repo: local
    hooks:
      - id: make-before-commit
        name: make before_commit
        entry: make before_commit
        language: system
        always_run: true
        pass_filenames: false
