name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - '**.rs'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install documentation tools
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme myst-parser autodoc-pydantic
          pip install -r requirements.txt

      - name: Generate Python API docs
        run: |
          mkdir -p docs/api
          sphinx-apidoc -o docs/api app/

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html || echo "Sphinx build skipped - docs directory not configured"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          cname: paddi.bullxyz.com  # Replace with your domain if you have one
