name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - '**.rs'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install documentation tools
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme myst-parser autodoc-pydantic
          pip install -r requirements.txt

      - name: Generate Python API docs
        run: |
          mkdir -p docs/api
          sphinx-apidoc -o docs/api app/

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html || echo "Sphinx build skipped - docs directory not configured"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_build/html

  # Deploy job
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
