# Cloud Run Service Configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: paddi-dashboard
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Maximum instances for cost control
        run.googleapis.com/max-scale: "10"
        # Minimum instances to reduce cold starts
        run.googleapis.com/min-scale: "1"
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: paddi-dashboard-sa
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/paddi-dashboard:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-api-key
                  key: api-key
            - name: GOOGLE_CLOUD_PROJECT
              value: "PROJECT_ID"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret-key
                  key: secret
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
